/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.zlikun.hadoop.avro;

@SuppressWarnings("all")
/** This is a message. */
@org.apache.avro.specific.AvroGenerated
public interface MessageProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MessageProtocol\",\"namespace\":\"com.zlikun.hadoop.avro\",\"doc\":\"This is a message.\",\"name\":\"Message\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"valid\",\"type\":\"boolean\"},{\"name\":\"content\",\"type\":\"string\"}]}],\"messages\":{\"sendMessage\":{\"doc\":\"message test\",\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"Message\"}}}");
  /**
   * message test
   */
  com.zlikun.hadoop.avro.Message sendMessage(com.zlikun.hadoop.avro.Message message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  /** This is a message. */
  public interface Callback extends MessageProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.zlikun.hadoop.avro.MessageProtocol.PROTOCOL;
    /**
     * message test
     * @throws java.io.IOException The async call could not be completed.
     */
    void sendMessage(com.zlikun.hadoop.avro.Message message, org.apache.avro.ipc.Callback<com.zlikun.hadoop.avro.Message> callback) throws java.io.IOException;
  }
}