/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.zlikun.hadoop.avro;  
@SuppressWarnings("all")
/** A user info model. */
@org.apache.avro.specific.AvroGenerated
public class User extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.zlikun.hadoop.avro\",\"doc\":\"A user info model.\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"birthday\",\"type\":\"long\"},{\"name\":\"favorite_number\",\"type\":[\"int\",\"null\"]},{\"name\":\"favorite_color\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public long birthday;
  @Deprecated public java.lang.Integer favorite_number;
  @Deprecated public java.lang.CharSequence favorite_color;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public User() {}

  /**
   * All-args constructor.
   */
  public User(java.lang.Long id, java.lang.CharSequence name, java.lang.Long birthday, java.lang.Integer favorite_number, java.lang.CharSequence favorite_color) {
    this.id = id;
    this.name = name;
    this.birthday = birthday;
    this.favorite_number = favorite_number;
    this.favorite_color = favorite_color;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return birthday;
    case 3: return favorite_number;
    case 4: return favorite_color;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: birthday = (java.lang.Long)value$; break;
    case 3: favorite_number = (java.lang.Integer)value$; break;
    case 4: favorite_color = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'birthday' field.
   */
  public java.lang.Long getBirthday() {
    return birthday;
  }

  /**
   * Sets the value of the 'birthday' field.
   * @param value the value to set.
   */
  public void setBirthday(java.lang.Long value) {
    this.birthday = value;
  }

  /**
   * Gets the value of the 'favorite_number' field.
   */
  public java.lang.Integer getFavoriteNumber() {
    return favorite_number;
  }

  /**
   * Sets the value of the 'favorite_number' field.
   * @param value the value to set.
   */
  public void setFavoriteNumber(java.lang.Integer value) {
    this.favorite_number = value;
  }

  /**
   * Gets the value of the 'favorite_color' field.
   */
  public java.lang.CharSequence getFavoriteColor() {
    return favorite_color;
  }

  /**
   * Sets the value of the 'favorite_color' field.
   * @param value the value to set.
   */
  public void setFavoriteColor(java.lang.CharSequence value) {
    this.favorite_color = value;
  }

  /** Creates a new User RecordBuilder */
  public static com.zlikun.hadoop.avro.User.Builder newBuilder() {
    return new com.zlikun.hadoop.avro.User.Builder();
  }
  
  /** Creates a new User RecordBuilder by copying an existing Builder */
  public static com.zlikun.hadoop.avro.User.Builder newBuilder(com.zlikun.hadoop.avro.User.Builder other) {
    return new com.zlikun.hadoop.avro.User.Builder(other);
  }
  
  /** Creates a new User RecordBuilder by copying an existing User instance */
  public static com.zlikun.hadoop.avro.User.Builder newBuilder(com.zlikun.hadoop.avro.User other) {
    return new com.zlikun.hadoop.avro.User.Builder(other);
  }
  
  /**
   * RecordBuilder for User instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<User>
    implements org.apache.avro.data.RecordBuilder<User> {

    private long id;
    private java.lang.CharSequence name;
    private long birthday;
    private java.lang.Integer favorite_number;
    private java.lang.CharSequence favorite_color;

    /** Creates a new Builder */
    private Builder() {
      super(com.zlikun.hadoop.avro.User.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.zlikun.hadoop.avro.User.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.birthday)) {
        this.birthday = data().deepCopy(fields()[2].schema(), other.birthday);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[3].schema(), other.favorite_number);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[4].schema(), other.favorite_color);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing User instance */
    private Builder(com.zlikun.hadoop.avro.User other) {
            super(com.zlikun.hadoop.avro.User.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.birthday)) {
        this.birthday = data().deepCopy(fields()[2].schema(), other.birthday);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.favorite_number)) {
        this.favorite_number = data().deepCopy(fields()[3].schema(), other.favorite_number);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.favorite_color)) {
        this.favorite_color = data().deepCopy(fields()[4].schema(), other.favorite_color);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Long getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.zlikun.hadoop.avro.User.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public com.zlikun.hadoop.avro.User.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.zlikun.hadoop.avro.User.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public com.zlikun.hadoop.avro.User.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'birthday' field */
    public java.lang.Long getBirthday() {
      return birthday;
    }
    
    /** Sets the value of the 'birthday' field */
    public com.zlikun.hadoop.avro.User.Builder setBirthday(long value) {
      validate(fields()[2], value);
      this.birthday = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'birthday' field has been set */
    public boolean hasBirthday() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'birthday' field */
    public com.zlikun.hadoop.avro.User.Builder clearBirthday() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'favorite_number' field */
    public java.lang.Integer getFavoriteNumber() {
      return favorite_number;
    }
    
    /** Sets the value of the 'favorite_number' field */
    public com.zlikun.hadoop.avro.User.Builder setFavoriteNumber(java.lang.Integer value) {
      validate(fields()[3], value);
      this.favorite_number = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'favorite_number' field has been set */
    public boolean hasFavoriteNumber() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'favorite_number' field */
    public com.zlikun.hadoop.avro.User.Builder clearFavoriteNumber() {
      favorite_number = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'favorite_color' field */
    public java.lang.CharSequence getFavoriteColor() {
      return favorite_color;
    }
    
    /** Sets the value of the 'favorite_color' field */
    public com.zlikun.hadoop.avro.User.Builder setFavoriteColor(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.favorite_color = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'favorite_color' field has been set */
    public boolean hasFavoriteColor() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'favorite_color' field */
    public com.zlikun.hadoop.avro.User.Builder clearFavoriteColor() {
      favorite_color = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public User build() {
      try {
        User record = new User();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.birthday = fieldSetFlags()[2] ? this.birthday : (java.lang.Long) defaultValue(fields()[2]);
        record.favorite_number = fieldSetFlags()[3] ? this.favorite_number : (java.lang.Integer) defaultValue(fields()[3]);
        record.favorite_color = fieldSetFlags()[4] ? this.favorite_color : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
